# Generated by Django 5.0 on 2025-01-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attended',
            field=models.BooleanField(default=True),
        ),
    ]
