# Generated by Django 5.0 on 2025-02-20 08:55

import base.models
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_attendance_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=base.models.employee_image_path),
        ),
    ]
