# Generated by Django 5.0 on 2025-02-21 10:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_employee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
