# Generated by Django 5.0 on 2025-02-21 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_foodmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='food_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='base.foodmenu'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
