# Generated by Django 5.0 on 2025-02-23 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_attendance_food_menu_alter_attendance_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='salary',
        ),
    ]
