# Generated by Django 5.0 on 2025-02-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_attendance_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Not Active')], default=False),
        ),
    ]
